### ISSUE TITLE
Record picture in SD

### ISSUE THREAD

**Issue by Vicentetomas** [Ponkabonk/ESP32-CAM-Demo#1]
Hello,
Is it possible to record the image directly in the sd?.
Thank you for your help.
Regards

**Comment by Ponkabonk** [comment]
I added the ability to save the image to the SD card.  I also changed the way the device connects to the WifI.  It just seems to work better for me on my network.  The ArduinoJson library has been updated too so you'll need to update that before you can compile the code.

**Comment by Ponkabonk** [comment]
Closing issue.
